package de.rub.nds.modelfuzzer.sut.io;

public enum TlsSymbol {
	RSA_CLIENT_HELLO,	
	RSA_CLIENT_KEY_EXCHANGE,
	PSK_CLIENT_HELLO,
	PSK_CLIENT_KEY_EXCHANGE,
	HEARTBEAT,
	ALERT_UNEXPECTED_MESSAGE,
	ALERT_CLOSE_NOTIFY,
	CHANGE_CIPHER_SPEC,
	FINISHED,
	APPLICATION, 
	HELLO_APPLICATION,
}