name: CI
on: [push, pull_request]

jobs:
  Build-and-Test:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    name: On ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk maven
      - name: Install
        run: |
          sudo update-java-alternatives --set java-1.8.0-openjdk-amd64
          java -version
          ./prepare.sh
      - name: Test
        run: |
          ./setup_sut.sh mbedtls-2.26.0
          java -jar target/dtls-fuzzer.jar args/mbedtls/learn_mbedtls_client_psk_rwalk -timeLimit "PT3M"
          cd output/mbedtls-2.26.0_client_psk_rwalk && ls -l && diff hyp3.dot learnedModel.dot
      - name: Test wolfssl-4.7.1r_client_psk
          ./setup_sut.sh wolfssl-4.7.1r
          java -jar target/dtls-fuzzer.jar args/wolfssl/learn_wolfssl_client_psk_rwalk -Dwolfssl.version=4.7.1r -queryLimit 1000 
          diff output/wolfssl_client_psk_rwalk/learnedModel.dot experiments/models/regression/clients/1000_queries/wolfssl-4.7.1r_client_psk/model.dot
