name: CI
on: [push, pull_request]

jobs:
  CTinyDTLS_Server_psk:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install DTLS-Fuzzer
        run: ./install.sh

      - name: Setup SUT
        run: ./setup_sut.sh ctinydtls

      - name: Test Contiki-NG TinyDTLS Server (psk)
        run: |
          java -jar target/dtls-fuzzer.jar args/ctinydtls/learn_ctinydtls_server_psk -roundLimit 5
          experiments/scripts/diff_hyps.sh experiments/models/regression/servers/rounds/ctinydtls_server_psk output/ctinydtls_server_psk 5

  CTinyDTLS_Client_psk:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install DTLS-Fuzzer
        run: ./install.sh

      - name: Setup SUT
        run: ./setup_sut.sh ctinydtls

      - name: Test Contiki-NG TinyDTLS Client (psk)
        run: |
          java -jar target/dtls-fuzzer.jar args/ctinydtls/learn_ctinydtls_client_psk -roundLimit 5
          experiments/scripts/diff_hyps.sh experiments/models/regression/clients/rounds/ctinydtls_client_psk output/ctinydtls_client_psk 5

  ETinyDTLS_Server_psk:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install DTLS-Fuzzer
        run: ./install.sh

      - name: Setup SUT
        run: ./setup_sut.sh etinydtls

      - name: Test Eclipse TinyDTLS Server (psk)
        run: |
          java -jar target/dtls-fuzzer.jar args/etinydtls/learn_etinydtls_server_psk -inputResponseTimeout CHANGE_CIPHER_SPEC:250 -roundLimit 5
          experiments/scripts/diff_hyps.sh experiments/models/regression/servers/rounds/etinydtls_server_psk output/etinydtls_server_psk 5

  ETinyDTLS_Client_psk:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install DTLS-Fuzzer
        run: ./install.sh

      - name: Setup SUT
        run: ./setup_sut.sh etinydtls

      - name: Test Eclipse TinyDTLS Client (psk)
        run: |
          java -jar target/dtls-fuzzer.jar args/etinydtls/learn_etinydtls_client_psk -inputResponseTimeout CHANGE_CIPHER_SPEC:250 -roundLimit 5
          experiments/scripts/diff_hyps.sh experiments/models/regression/clients/rounds/etinydtls_client_psk output/etinydtls_client_psk 5

  JSSE-12-0-2_Server_ecdhe_cert_req:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install DTLS-Fuzzer
        run: ./install.sh

      - name: Setup SUT
        run: ./setup_sut.sh jsse-12.0.2

      - name: Test jsse-12.0.2 Server (ecdhe_cert_req)
        run: |
          java -jar target/dtls-fuzzer.jar args/jsse/learn_jsse_server_ecdhe_cert_req -Djsse.version=12.0.2 -roundLimit 5
          experiments/scripts/diff_hyps.sh experiments/models/regression/servers/rounds/jsse-12.0.2_server_ecdhe_cert_req output/jsse-12.0.2_server_ecdhe_cert_req 5

  JSSE-12-0-2_Client_ecdhe_cert:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install DTLS-Fuzzer
        run: ./install.sh

      - name: Setup SUT
        run: ./setup_sut.sh jsse-12.0.2

      - name: Test jsse-12.0.2 Client (ecdhe_cert)
        run: |
          java -jar target/dtls-fuzzer.jar args/jsse/learn_jsse_client_ecdhe_cert -Djsse.version=12.0.2 -roundLimit 5
          experiments/scripts/diff_hyps.sh experiments/models/regression/clients/rounds/jsse-12.0.2_client_ecdhe_cert output/jsse-12.0.2_client_ecdhe_cert 5

  Mbedtls-2-26-0_Server_all_cert_req:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install DTLS-Fuzzer
        run: ./install.sh

      - name: Setup SUT
        run: ./setup_sut.sh mbedtls-2.26.0

      - name: Test mbedtls-2.26.0 Server (all_cert_req)
        run: |
          java -jar target/dtls-fuzzer.jar args/mbedtls/learn_mbedtls_server_all_cert_req -Dmbedtls.version=2.26.0 -roundLimit 5
          experiments/scripts/diff_hyps.sh experiments/models/regression/servers/rounds/mbedtls-2.26.0_server_all_cert_req output/mbedtls-2.26.0_server_all_cert_req 5

  Mbedtls-2-26-0_Client_dhe_ecdhe_rsa_eneg:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install DTLS-Fuzzer
        run: ./install.sh

      - name: Setup SUT
        run: ./setup_sut.sh mbedtls-2.26.0

      - name: Test mbedtls-2.26.0 Client (dhe_ecdhe_rsa_cert_reneg)
        run: |
          java -jar target/dtls-fuzzer.jar args/mbedtls/learn_mbedtls_client_dhe_ecdhe_rsa_cert_reneg -Dmbedtls.version=2.26.0 -roundLimit 5
          experiments/scripts/diff_hyps.sh experiments/models/regression/clients/rounds/mbedtls-2.26.0_client_dhe_ecdhe_rsa_cert_reneg output/mbedtls-2.26.0_client_dhe_ecdhe_rsa_cert_reneg 5

  OpenSSL-1-1-1k_Server_all_cert_req:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install DTLS-Fuzzer
        run: ./install.sh

      - name: Setup SUT
        run: ./setup_sut.sh openssl-1.1.1k

      - name: Test openssl-1.1.1k Server (all_cert_req)
        run: |
          java -jar target/dtls-fuzzer.jar args/openssl/learn_openssl_server_all_cert_req -Dopenssl.version=1.1.1k -roundLimit 5
          experiments/scripts/diff_hyps.sh experiments/models/regression/servers/rounds/openssl-1.1.1k_server_all_cert_req output/openssl-1.1.1k_server_all_cert_req 5

  OpenSSL-1-1-1k_Client_dhe_ecdhe_rsa_eneg:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install DTLS-Fuzzer
        run: ./install.sh

      - name: Setup SUT
        run: ./setup_sut.sh openssl-1.1.1k

      - name: Test openssl-1.1.1k Client (dhe_ecdhe_rsa_reneg)
        run: |
          java -jar target/dtls-fuzzer.jar args/openssl/learn_openssl_client_dhe_ecdhe_rsa_cert_reneg -Dopenssl.version=1.1.1k -roundLimit 5
          experiments/scripts/diff_hyps.sh experiments/models/regression/clients/rounds/openssl-1.1.1k_client_dhe_ecdhe_rsa_cert_reneg output/openssl-1.1.1k_client_dhe_ecdhe_rsa_cert_reneg 5

  PionDTLS-2-0-9_Server_psk:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-20.04 # due to needing an old version of golang
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install DTLS-Fuzzer
        run: ./install.sh

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Setup SUT
        run: ./setup_sut.sh piondtls-2.0.9

      - name: Test piondtls-2.0.9 Server (psk)
        run: |
          java -jar target/dtls-fuzzer.jar args/piondtls/learn_piondtls_server_psk -Dpiondtls.version=2.0.9 -roundLimit 5
          experiments/scripts/diff_hyps.sh experiments/models/regression/servers/rounds/piondtls-2.0.9_server_psk output/piondtls-2.0.9_server_psk 5

  PionDTLS-2-0-9_Client_psk:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-20.04 # due to needing an old version of golang
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install DTLS-Fuzzer
        run: ./install.sh

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Setup SUT
        run: ./setup_sut.sh piondtls-2.0.9

      - name: Test piondtls-2.0.9 Client (psk)
        run: |
          java -jar target/dtls-fuzzer.jar args/piondtls/learn_piondtls_client_psk -Dpiondtls.version=2.0.9 -roundLimit 7
          experiments/scripts/diff_hyps.sh experiments/models/regression/clients/rounds/piondtls-2.0.9_client_psk output/piondtls-2.0.9_client_psk 7

  Scandium-2-0-0-M16_Server_ecdhe_cert_req:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install DTLS-Fuzzer
        run: ./install.sh

      - name: Setup SUT
        run: ./setup_sut.sh scandium-2.0.0-M16

      - name: Test scandium-2.0.0-M16 Server (ecdhe_cert_req)
        run: |
          java -jar target/dtls-fuzzer.jar args/scandium/learn_scandium_server_ecdhe_cert_req -Dscandium.version=2.0.0-M16 -roundLimit 5
          experiments/scripts/diff_hyps.sh experiments/models/regression/servers/rounds/scandium-2.0.0-M16_server_ecdhe_cert_req output/scandium-2.0.0-M16_server_ecdhe_cert_req 5

  Scandium-2-0-0-M16_Client_ecdhe_cert:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install DTLS-Fuzzer
        run: ./install.sh

      - name: Setup SUT
        run: ./setup_sut.sh scandium-2.0.0-M16

      - name: Test scandium-2.0.0-M16 Client (ecdhe_cert)
        run: |
          # we are running just two rounds here because producing the third hypothesis takes too long
          java -jar target/dtls-fuzzer.jar args/scandium/learn_scandium_client_ecdhe_cert -Dscandium.version=2.0.0-M16 -roundLimit 2
          experiments/scripts/diff_hyps.sh experiments/models/regression/clients/rounds/scandium-2.0.0-M16_client_ecdhe_cert output/scandium-2.0.0-M16_client_ecdhe_cert 2

  WolfSSL-4-7-1r_Server_psk:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install DTLS-Fuzzer
        run: ./install.sh

      - name: Setup SUT
        run: ./setup_sut.sh wolfssl-4.7.1r

      - name: Test wolfssl-4.7.1r Server (psk)
        run: |
          java -jar target/dtls-fuzzer.jar args/wolfssl/learn_wolfssl_server_psk -Dwolfssl.version=4.7.1r -roundLimit 5
          experiments/scripts/diff_hyps.sh experiments/models/regression/servers/rounds/wolfssl-4.7.1r_server_psk output/wolfssl-4.7.1r_server_psk 5

  WolfSSL-4-7-1r_Client_psk:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install DTLS-Fuzzer
        run: ./install.sh

      - name: Setup SUT
        run: ./setup_sut.sh wolfssl-4.7.1r

      - name: Test wolfssl-4.7.1r Client (psk)
        run: |
          java -jar target/dtls-fuzzer.jar args/wolfssl/learn_wolfssl_client_psk -Dwolfssl.version=4.7.1r -roundLimit 6
          experiments/scripts/diff_hyps.sh experiments/models/regression/clients/rounds/wolfssl-4.7.1r_client_psk output/wolfssl-4.7.1r_client_psk 6
