name: CI
on: [push, pull_request]

jobs:
  Build-Container:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    name: On ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk maven
          sudo update-java-alternatives --set java-1.8.0-openjdk-amd64
          java -version
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install DTLS-Fuzzer
        run: ./install.sh
      - name: Setup Suts
        run: |
          ./setup_sut.sh mbedtls-2.26.0
          ./setup_sut.sh wolfssl-4.7.1r
      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: |
            suts
            target
          key: dtls-fuzzer-suts
      - name: Test mbedtls-2.26.0 Server (all_cert_req)
        run: |
          java -jar target/dtls-fuzzer.jar args/mbedtls/learn_mbedtls_server_all_cert_req -Dmbedtls.version=2.26.0 -testLimit 1000
          diff output/mbedtls-2.26.0_server_all_cert_req/learnedModel.dot experiments/models/regression/servers/1000_queries/mbedtls-2.26.0_server_all_cert_req/model.dot
      - name: Test mbedtls-2.26.0 Client (dhe_ecdhe_rsa_reneg)
        run: |
          java -jar target/dtls-fuzzer.jar args/mbedtls/learn_mbedtls_client_dhe_ecdhe_rsa_cert_reneg -Dmbedtls.version=2.26.0 -testLimit 1000
          diff output/mbedtls-2.26.0_client_dhe_ecdhe_rsa_cert_reneg/learnedModel.dot experiments/models/regression/clients/1000_queries/mbedtls-2.26.0_client_dhe_ecdhe_rsa_cert_reneg/model.dot
      - name: Test wolfssl-4.7.1r Server (psk)
        run: |
          java -jar target/dtls-fuzzer.jar args/wolfssl/learn_wolfssl_server_psk -Dwolfssl.version=4.7.1r -testLimit 1000
          diff output/wolfssl-4.7.1r_server_psk/learnedModel.dot experiments/models/regression/servers/1000_queries/wolfssl-4.7.1r_server_psk/model.dot
      - name: Test wolfssl-4.7.1r Client (psk)
        run: |
          java -jar target/dtls-fuzzer.jar args/wolfssl/learn_wolfssl_client_psk -Dwolfssl.version=4.7.1r -testLimit 1000
          diff output/wolfssl-4.7.1r_client_psk/learnedModel.dot experiments/models/regression/clients/1000_queries/wolfssl-4.7.1r_client_psk/model.dot
